//! Optional Helix `theme.toml` -> CSS stylesheet.
//!
//! Each scope key becomes a rule whose selector matches the most specific class
//! the HTML backend emits: `keyword.control` -> `.keyword-control`. Palette
//! names are resolved via the theme's `[palette]` table.

use std::collections::HashMap;

use anyhow::{Context, Result};
use toml::Value;

/// Render a `theme.toml` string into a CSS stylesheet.
pub fn to_css(theme_toml: &str) -> Result<String> {
    let value: Value = toml::from_str(theme_toml).context("parsing theme.toml")?;
    let table = value.as_table().context("theme.toml is not a table")?;

    let palette: HashMap<String, String> = table
        .get("palette")
        .and_then(Value::as_table)
        .map(|t| {
            t.iter()
                .filter_map(|(k, v)| v.as_str().map(|s| (k.clone(), s.to_string())))
                .collect()
        })
        .unwrap_or_default();

    let resolve = |color: &str| -> String {
        palette
            .get(color)
            .cloned()
            .unwrap_or_else(|| color.to_string())
    };

    let mut css = String::from("/* generated by dathan from theme.toml */\n");
    let mut scopes: Vec<(&String, &Value)> = table
        .iter()
        .filter(|(k, _)| k.as_str() != "palette" && k.as_str() != "inherits")
        .collect();
    scopes.sort_by_key(|(k, _)| k.as_str());

    for (scope, style) in scopes {
        let mut decls = Vec::new();

        match style {
            Value::String(color) => decls.push(format!("color: {}", resolve(color))),
            Value::Table(t) => {
                if let Some(fg) = t.get("fg").and_then(Value::as_str) {
                    decls.push(format!("color: {}", resolve(fg)));
                }
                if let Some(bg) = t.get("bg").and_then(Value::as_str) {
                    decls.push(format!("background-color: {}", resolve(bg)));
                }
                if let Some(mods) = t.get("modifiers").and_then(Value::as_array) {
                    for m in mods.iter().filter_map(Value::as_str) {
                        match m {
                            "bold" => decls.push("font-weight: bold".into()),
                            "italic" => decls.push("font-style: italic".into()),
                            "underlined" => decls.push("text-decoration: underline".into()),
                            "crossed_out" => decls.push("text-decoration: line-through".into()),
                            "dim" => decls.push("opacity: 0.7".into()),
                            _ => {}
                        }
                    }
                }
                if t.get("underline").is_some() {
                    decls.push("text-decoration: underline".into());
                }
            }
            _ => {}
        }

        if decls.is_empty() {
            continue;
        }
        css.push_str(&format!(
            ".{} {{ {}; }}\n",
            css_class(scope),
            decls.join("; ")
        ));
    }

    Ok(css)
}

/// `keyword.control` -> `keyword-control` (matches the HTML backend's most
/// specific class).
fn css_class(scope: &str) -> String {
    scope.replace('.', "-")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn palette_and_modifiers() {
        let theme = r##"
"keyword.control" = { fg = "blue", modifiers = ["bold"] }
comment = "gray"
[palette]
blue = "#0000ff"
gray = "#808080"
"##;
        let css = to_css(theme).unwrap();
        assert!(css.contains(".keyword-control { color: #0000ff; font-weight: bold; }"));
        assert!(css.contains(".comment { color: #808080; }"));
    }
}
